server:
  port: 8080
spring:
  application:
    name: order-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        cluster-name: BJ
#        ephemeral: false #非临时实例
#        namespace: 8a61ef37-2daa-402f-8b1d-5363629c5c87
    loadbalancer:
      nacos:
        enabled: true
    sentinel:
      transport:
        dashboard: 127.0.0.1:8100 #sentinel控制台地址
      web-context-unify: false #关闭context聚合

# 设置 Mybatis 的 xml 保存路径
mybatis:
  configuration: # 配置打印 MyBatis 执行的 SQL
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #自动驼峰转换
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %c %M %L [%thread] %m%n'
    file: '%d{HH:mm:ss.SSS} %c %M %L [%thread] %m%n'

feign:
  sentinel:
    enabled: true