server:
  port: 7071
spring:
  application:
    name: config-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoli79/config-server.git  #配置文件Git 地址
          default-label: master #配置文件分支
          search-paths: config  #配置文件所在根目录
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %c %M %L [%thread] %m%n'
    file: '%d{HH:mm:ss.SSS} %c %M %L [%thread] %m%n'